debug: false
interval: 8m

device:
  name: My Device
  manufacturer: My Manufacturer
  model: My Model

sensors:
  sensor-1: 
    faker: { measures: [temperature, humidity] }
  sensor-2:
    am2320: {}
  sensor-2:
    ds18b20: { identifier: 0122334455ff }

publishers:
  pub-1:
    stdout: {}
  pub-2:
    mqtt: { host: 192.168.33.1 }
