services:
  app:
    build:
      context: .
      # dockerfile: Dockerfile.crossbuild

    volumes:
      - ${PWD}/config.yml:/app/config.yml:ro

    group_add:
      - 115 # getent group i2c

    devices:
      - /dev/i2c-1